fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.5.1'
    stdlibplus:
      repo: 'https://github.com/juliengk/puppet-stdlibplus.git'
      ref: 'v0.1.8'
  symlinks:
    env: "#{source_dir}"
